// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCMla8RLFa_5dVk89TUSuqK-Qwr3X0gfw',
    appId: '1:1083691584230:web:f9506918470c69148e4927',
    messagingSenderId: '1083691584230',
    projectId: 'menu-nau-an-4c004',
    authDomain: 'menu-nau-an-4c004.firebaseapp.com',
    storageBucket: 'menu-nau-an-4c004.firebasestorage.app',
    measurementId: 'G-RY0GLRPSVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHX0hj8f5PQz0tRtTAUyMYcvC7XbbsvQU',
    appId: '1:1083691584230:android:dd9f8237425cb3fd8e4927',
    messagingSenderId: '1083691584230',
    projectId: 'menu-nau-an-4c004',
    storageBucket: 'menu-nau-an-4c004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbkRkhoYrmshUQb4Y1qwWQ0FaPfzUOe0s',
    appId: '1:1083691584230:ios:79041b652827c2238e4927',
    messagingSenderId: '1083691584230',
    projectId: 'menu-nau-an-4c004',
    storageBucket: 'menu-nau-an-4c004.firebasestorage.app',
    iosBundleId: 'com.example.menuNauAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbkRkhoYrmshUQb4Y1qwWQ0FaPfzUOe0s',
    appId: '1:1083691584230:ios:79041b652827c2238e4927',
    messagingSenderId: '1083691584230',
    projectId: 'menu-nau-an-4c004',
    storageBucket: 'menu-nau-an-4c004.firebasestorage.app',
    iosBundleId: 'com.example.menuNauAn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCMla8RLFa_5dVk89TUSuqK-Qwr3X0gfw',
    appId: '1:1083691584230:web:11a9720255bcfedd8e4927',
    messagingSenderId: '1083691584230',
    projectId: 'menu-nau-an-4c004',
    authDomain: 'menu-nau-an-4c004.firebaseapp.com',
    storageBucket: 'menu-nau-an-4c004.firebasestorage.app',
    measurementId: 'G-PLD0ZGJZ31',
  );
}
